services:

  backoffice:
    image: dockdiary/backoffice:latest
    restart: always
    container_name: backoffice
    ports:
      - "8081:8081"
    environment:
      - "SPRING_DATASOURCE_URL=jdbc:postgresql://mydb:5432/${POSTGRES_DATABASE}"
      - "SPRING_DATASOURCE_USERNAME=${POSTGRES_USERNAME}"
      - "SPRING_DATASOURCE_PASSWORD=${POSTGRES_ROOT_PASSWORD}"
      - "JWT_SECRET=${BO_JWT_SECRET}"
      - TZ=Asia/Seoul
    networks:
      - serverdb_default

networks:
  serverdb_default:
    external: true
