spring.application.name=BackOffice

spring.datasource.url=jdbc:postgresql://localhost:5432/mydb
spring.datasource.username=postgres
spring.datasource.password=postpassword
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.port=8081

jwt.secret=BackOfficeSecretKey2026!@#SuperLongKey
jwt.expiration=86400000

springdoc.swagger-ui.path=/swagger
springdoc.api-docs.path=/v3/api-docs
